### ISSUE TITLE
PieDonut does not show Donut labels with low percentages

### ISSUE THREAD

**Issue by singlecellfan** [cardiomoon/webr#9]
Hi,

first of all I really like the PieDonut function. Great job!
Unfortunately when I plot my data the Donuts that contribute with a low percentage are not labeled (see example).

Do you know about this issue and is there a possibility to fix it?

Thanks in advance!

![test_piedonut](https://user-images.githubusercontent.com/79158757/108091750-4b820580-707c-11eb-9d92-b2a131abd2cb.png)

**Comment by cardiomoon** [comment]
You can set the showRatioThreshold argument with the low value(e.g. 0.001) when call PieDonut() function.
`
browser=c("MSIE","Firefox","Chrome","Safari","Opera")
share=c(50,21.9,10.8,6.5,1.8)
df=data.frame(browser,share)
PieDonut(df,aes(browser,count=share),r0=0.7,start=3*pi/2,labelpositionThreshold=0.1)
PieDonut(df,aes(browser,count=share),r0=0.7,start=3*pi/2,labelpositionThreshold=0.1,showRatioThreshold = 0.01)
`
